name: Build Game Theme Music

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: ['main']
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm install

      - name: Build frontend
        run: pnpm run build

      - name: Download Decky Plugin CLI
        run: |
          mkdir $(pwd)/cli
          curl -L -o $(pwd)/cli/decky "https://github.com/SteamDeckHomebrew/cli/releases/latest/download/decky-linux-x86_64"
          chmod +x $(pwd)/cli/decky

      - name: Build plugin
        run: |
          $(pwd)/cli/decky plugin build $(pwd)
          unzip "out/Game Theme Music.zip" -d "out/Game Theme Music"

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: SDH-GameThemeMusic
          path: |
            ./out/Game Theme Music/*
